#+SETUPFILE: ./config/setupfile.org


#+BEGIN_EXPORT latex
\thispagestyle{firststyle}
\IssueTitle{Market Discipline or a Fallout}
\NewsAuthor{Mauricio Rosal, \small\it Chief Economist, PhD}
\NewsEmail{joao.rosal@bgcpartners.com}
\JournalIssue

    \begin{tcolorbox}[colbak=red!5!white, colframe=red!0!white]
      \NewsItem{Market Discipline or a Fallout?}
      \begin{compactitem}
      \item \textit{We understand the balance of risks have changed, unfortunatley, not for the better.}
      \item \textit{A muddling through type of social security reform is becoming more likely as opposed to a material one.}
      \item \textit{This implies a two-fold path going foward: a) market discipline forces a meaningful reform, or b) political forebearnace leads to negative re-pricing for the longer term.}
      \end{compactitem}
    \end{tcolorbox}
\vspace{-0.5cm}
#+END_EXPORT

* The Two-fold paths
#+ATTR_LATEX: :environment compactitem :options [$\diamond$]
- *Balance of risks have changed*. The latest flow of news have
  confirmed the difficulties of Mr. Temer to approve the social
  secutiry reform as is. While some type of compromising have been
  expected from the outset, we believe the latest announcement to
  leave State civil servants out of the reform has opened a pandora
  box, making it is difficult to predict what is going to come out of
  it.

  More specifically, once one makes such a type of compromising
  involving specific classes of workers, the incentives in place are
  such that other classes should soon start to lobby for
  favoritism. In addition, there is also the interest of less
  organized citizens, such as those leaving off social benefits in
  many corners of the country, who hold great voting
  relevance. Thence, once sums all that up, the budget of acceptable
  concessions from the fiscal adjustment standpoint may start to fall
  short of the mounting pressures.

#+BEGIN_EXPORT latex
\begin{figure}[h]\centering
\subfloat[#]{
\label{fig:spreads}
\includegraphics[width=6.5cm]{./images/csv.png}

}
\subfloat[#]{
\label{fig:vix}
\includegraphics[width=6.5cm]{./images/vix.png}
}

\end{figure}
#+END_EXPORT

- *A two-fold path*. In light of the fore mentioned, the easy path
  towards a reform that comprises a) increases the minimum retirement
  age to 65 for both genders; b) ends with retirement of period of
  contribution of the system; and c) encompasses rural, urban, private
  and public workers alike is no longer possible. In fact, in order to
  reach a compromise that contemplates parts of either of these
  topics, there ought to be pressure in the opposite direction, and
  the only possible candidate to looks in the positions to do so is
  the market.

  In fact, Brazilian credit spreads as in \ref{fig:spreads}, it's been
  standing about 90bps above Mexico's year-to-date, a country holding
  a sovereign credit rating about 4 notches above Brazil's. No doubt,
  it entails a rather benign vision towards the country's outlook, in
  particular, with respect to the country social security system.
  Hence, should this perception changes significantly, there is plenty
  of room for things to turn sour. In fact, the recent moves
  concerning the social security reform have been shrugged off by the
  market, and the volatility of Brazilian assets have clearly take off
  way from the US's benchmark.

  Hence, the question: will the political class remain oblivious to
  that and follow their own agenda, or will the kneel to market
  pressures? We thinks latter of the most likely candidate, but with
  2018 general elections take over their agenda, one should not
  dismiss the former altogether.



#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT




* Forecastsn


#+LATEX:\rowcolors{2}{grey!15}{white}
#+INCLUDE: "./org/forecast.org"

#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT


* Disclaimer
[[http://www.bgcpartners.com]] \\
\textbf{CONFIDENTIAL:} This document has been sent to you by one of
the BGC entities (collectively BGC) Please see important legal
information and disclaimer relating to this mail at the following
links: http://www.bgcpartners.com/disclaimers/

Please see for BGC Disclosures. The link contains company and FCA
registration numbers. This e-mail, including its contents and
attachments, if any, are confidential. If you are not the named
recipient please notify the sender and immediately delete it. You may
not disseminate, distribute, or forward this e-mail message or
disclose its contents to anybody else. Copyright and any other
intellectual property rights in its contents are the sole property of
BGC and its affiliates. E-mail transmission cannot be guaranteed to be
secure or error-free.  The sender therefore does not accept liability
for any errors or omissions in the contents of this message which
arise as a result of e-mail transmission.  If verification is required
please request a hard-copy version. Although we routinely screen for
viruses, addressees should check this e-mail and any attachments for
viruses. We make no representation or warranty as to the absence of
viruses in this e-mail or any attachments. Please note that to ensure
regulatory compliance and for the protection of our customers and
business, we may monitor and read e-mails sent to and from our
server(s).  The registered offices of the BGC entities are at 1
Churchill Place, London, E14 5RD.  For any issues arising from this
email please reply to the sender.  The FCA register appears at
http://www.FCA.org.uk/register/.  The FCA regulates the financial
services industry in the United Kingdom and is located at 25 The North
Colonnade, Canary Wharf, London, E14 5HS.  BGC Financial LP CFTC Rule
1.55(K) Firm Specific Disclosure Statement

* COMMENT Local Variables
# Local Variables:
# eval: (load-file "./elisp/publishing.el")
# END:
